openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: /v1/api
security:
  - bearer-atk-token: []
tags:
  - name: Auth
paths:
  /projects:
    get:
      tags:
        - Projects
      operationId: getProjects
      description: 'Get all users projects'
      responses:
        '200':
          description: Authentication valid - token in body returned
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/ProjectDto'
components:
  schemas:
    ProjectDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        ownerId:
          type: integer
          format: int64
        title:
          type: string
        ideaImage:
          type: string
        solutionImage:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        points:
          type: integer
        creationTimestamp:
          type: integer
          format: int64
    IdeaDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        ownerId:
          type: integer
          format: int64
        additionalInfo:
          type: string
        tags:
          type: array
          items:
            type: string
        comments:
          type: array
          items:
            $ref: '#/components/schemas/CommentDto'
        points:
          type: integer
        creationTimestamp:
          type: integer
          format: int64
    CommentDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        ownerId:
          type: integer
          format: int64
        content:
          type: string