openapi: 3.0.2
info:
  title: API
  version: 1.0.0
servers:
  - url: /v1/api
security:
  - bearer-atk-token: []
tags:
  - name: Projects
  - name: Ideas
paths:
  /projects:
    get:
      tags:
        - Projects
      operationId: getProjects
      description: 'Get all users projects ordered by most recent'
      responses:
        '200':
          description: List of projects
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProjectDto'
    post:
      tags:
        - Projects
      operationId: addProject
      description: 'Add project by user'
      parameters:
        - in: header
          name: X-User-ID
          schema:
            type: integer
          required: true
      requestBody:
        description: Optional description in *Markdown*
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProjectRequest'
      responses:
        '204':
          description: Returned when project creation operation is successful

  /ideas:
    get:
      tags:
        - Ideas
      operationId: getIdeas
      description: 'Get all users ideas'
      responses:
        '200':
          description: List of ideas
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/IdeaDto'

  /ideas/{ideaId}:
    get:
      tags:
        - Ideas
      operationId: getIdeaDetails
      description: 'Get specific idea details'
      parameters:
        - in: path
          name: ideaId
          schema:
            type: integer
            format: int64
          required: true
          description: Numeric ID of the idea to get
      responses:
        '200':
          description: Idea details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdeaDetailsDto'
components:
  schemas:
    CreateProjectRequest:
      type: object
      properties:
        title:
          type: string
        ideaImage:
          type: string
        solutionImage:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
      required:
        - title
        - ideaImage
        - solutionImage
        - description
    ProjectDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        ownerId:
          type: integer
          format: int64
        title:
          type: string
        ideaImage:
          type: string
        solutionImage:
          type: string
        description:
          type: string
        tags:
          type: array
          items:
            type: string
        points:
          type: integer
        creationTimestamp:
          type: integer
          format: int64
    IdeaDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        additionalInfo:
          type: string
        points:
          type: integer
        creationTimestamp:
          type: integer
          format: int64
    IdeaDetailsDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        owner:
          $ref: '#/components/schemas/OwnerDto'
        additionalInfo:
          type: string
        comments:
          type: array
          items:
            $ref: '#/components/schemas/CommentDto'
        tags:
          type: array
          items:
            type: string
        points:
          type: integer
        creationTimestamp:
          type: integer
          format: int64
    CommentDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        owner:
          $ref: '#/components/schemas/OwnerDto'
        content:
          type: string
    OwnerDto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string